"""rename both tables and add parsed text to resume

Revision ID: fd684d0cd260
Revises: 
Create Date: 2025-09-15 11:52:50.640045

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fd684d0cd260'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('file','resume')
    op.rename_table('job_description','job')
    op.add_column('resume',
        sa.Column('parsed_text', sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume','parsed_text')
    op.rename_table('resume','file')
    op.rename_table('job','job_description')
    # ### end Alembic commands ###
